Dev add inscription relationship
jandrovins/idea pull request #4
Opened 2021-09-23 20:26 UTC by sflorezs1

Added some missing relationships between classes, and implemented the inscription system.

2021-09-23 20:32 UTC, GrayDiamond493 approved these changes

2021-09-23 23:08 UTC, jandrovins requested changes
I leaved some comments on specific suggestions. Let me know your thoughts.

Every change not mentioned is OK with me.

2021-09-23 23:08 UTC, jandrovins commented on resources/views/courses/show.blade.php
>                      <h5><span class="font-weight-bold">@lang("messages.course.id"):</span>
Around these lines should be listed the user author of the course too.

2021-09-23 23:08 UTC, jandrovins commented on app/Models/Inscription.php
> +    //
Remember to add the comment listing all attributes of this class.

2021-09-23 23:08 UTC, jandrovins commented on app/Models/User.php
>       */
I guess the bold developers of Laravel do not add the comment listing all attributes of this class. Could you add it?

2021-09-24 20:22 UTC, jandrovins approved these changes

2021-09-24 22:29 UTC, merged